% Library script to store crystallographic data of d-block transition
% metals for various solid-state calculations
% Data taken from CRC Handbook of Chemistry and Physics 83rd Edition
% Carter Reed

function metalsdb = metalDatabase()

% Lattice parameters are in nm
% SK 2-center parameters (SK and onsite) are in Rydbergs (Ry) taken from 
% Papaconstantopoulos "Handbook of the Band Structure of Elemental Solids"
% Commented out metals may be added in a later update

% 3d metals
metalsdb.sc = struct('name'     , 'Scandium', ...
                     'structure', 'HCP', ...
                     'Z'        , 21, ...
                     'Valence'  , 3); 
metalsdb.sc.latParam = struct('a'        , 0.33088, ...
                              'c'        , 0.52680);
metalsdb.sc.SK = struct('Vsssig'   ,-0.05610, ...
                        'Vspsig'   , 0.07388, ...
                        'Vppsig'   , 0.09050, ...
                        'Vpppi'    ,-0.01454, ...
                        'Vpdsig'   , 0.05269, ...
                        'Vpdpi'    ,-0.01963, ...
                        'Vsdsig'   , 0.04311, ...
                        'Vddsig'   ,-0.04407, ...
                        'Vddpi'    , 0.02646, ...
                        'Vdddel'   ,-0.00391);
metalsdb.sc.onsite = struct('s' ,0.74560, ...
                            'p' ,0.91737, ...
                            'd0',0.57614, ...
                            'd1',0.57334, ...
                            'd2',0.58139);

metalsdb.ti = struct('name'     , 'Titantium', ...
                     'structure', 'HCP', ...
                     'Z'        , 22, ...
                     'Valence'  , 4); 
metalsdb.ti.latParam = struct('a'        , 0.29506, ...
                              'c'        , 0.46835);
metalsdb.ti.SK = struct('Vsssig'   ,-0.06104, ...
                        'Vspsig'   , 0.07517, ...
                        'Vppsig'   , 0.09812, ...
                        'Vpppi'    ,-0.02239, ...
                        'Vpdsig'   , 0.06046, ...
                        'Vpdpi'    ,-0.02427, ...
                        'Vsdsig'   , 0.04732, ...
                        'Vddsig'   ,-0.05195, ...
                        'Vddpi'    , 0.03080, ...
                        'Vdddel'   ,-0.00442);
metalsdb.ti.onsite = struct('s' ,0.90402, ...
                            'p' ,1.15021, ...
                            'd0',0.68539, ...
                            'd1',0.68485, ...
                            'd2',0.69467);

metalsdb.v  = struct('name'     , 'Vanadium', ...
                     'structure', 'BCC', ...
                     'Z'        , 23, ...
                     'Valence'  , 5); 
metalsdb.v.latParam = struct('a'        , 0.30240);
metalsdb.v.SK = struct('Vsssig'   ,-0.12571, ...
                       'Vspsig'   , 0.14761, ...
                       'Vppsig'   , 0.22655, ...
                       'Vpppi'    , 0.03351, ...
                       'Vpdsig'   ,-0.10435, ...
                       'Vpdpi'    , 0.02223, ...
                       'Vsdsig'   ,-0.07643, ...
                       'Vddsig'   ,-0.06196, ...
                       'Vddpi'    , 0.03633, ...
                       'Vdddel'   ,-0.00223);
metalsdb.v.onsite = struct('s' ,1.18662, ...
                           'p' ,1.73152, ...
                           'd1',0.79925, ...
                           'd2',0.75975);

metalsdb.cr = struct('name'     , 'Chromium', ...
                     'structure', 'BCC', ...
                     'Z'        , 24, ...
                     'Valence'  , 6); 
metalsdb.cr.latParam = struct('a'        , 0.28848);
metalsdb.cr.SK = struct('Vsssig'   ,-0.13748, ...
                        'Vspsig'   , 0.16377, ...
                        'Vppsig'   , 0.24993, ...
                        'Vpppi'    , 0.03579, ...
                        'Vpdsig'   ,-0.10654, ...
                        'Vpdpi'    , 0.02331, ...
                        'Vsdsig'   ,-0.07784, ...
                        'Vddsig'   ,-0.06208, ...
                        'Vddpi'    , 0.03675, ...
                        'Vdddel'   ,-0.00268);
metalsdb.cr.onsite = struct('s' ,1.27653, ...
                            'p' ,1.87795, ...
                            'd1',0.80247, ...
                            'd2',0.76581);

% Mn


metalsdb.fe = struct('name'     , 'Iron', ...
                     'structure', 'BCC', ...
                     'Z'        , 26, ...
                     'Valence'  , 8); 
metalsdb.fe.latParam = struct('a'        , 0.28665);
metalsdb.fe.SK = struct('Vsssig'   ,-0.12950, ...
                        'Vspsig'   , 0.17363, ...
                        'Vppsig'   , 0.25741, ...
                        'Vpppi'    , 0.02422, ...
                        'Vpdsig'   ,-0.08485, ...
                        'Vpdpi'    , 0.01778, ...
                        'Vsdsig'   ,-0.06115, ...
                        'Vddsig'   ,-0.04541, ...
                        'Vddpi'    , 0.02714, ...
                        'Vdddel'   ,-0.00260);
metalsdb.fe.onsite = struct('s' ,1.13516, ...
                            'p' ,1.81739, ...
                            'd1',0.64840, ...
                            'd2',0.62960);

% Co

metalsdb.ni = struct('name'     , 'Nickel', ...
                     'structure', 'FCC', ...
                     'Z'        , 28, ...
                     'Valence'  , 10); 
metalsdb.ni.latParam = struct('a'        , 0.35240);
metalsdb.ni.SK = struct('Vsssig'   ,-0.08657, ...
                        'Vspsig'   , 0.13148, ...
                        'Vppsig'   , 0.21620, ...
                        'Vpppi'    , 0.00965, ...
                        'Vpdsig'   ,-0.03015, ...
                        'Vpdpi'    , 0.02725, ...
                        'Vsdsig'   ,-0.03056, ...
                        'Vddsig'   ,-0.03441, ...
                        'Vddpi'    , 0.02534, ...
                        'Vdddel'   ,-0.00597);
metalsdb.ni.onsite = struct('s' ,0.99144, ...
                            'p' ,1.52711, ...
                            'd1',0.48464, ...
                            'd2',0.48665);

metalsdb.cu = struct('name'     , 'Copper', ...
                     'structure', 'FCC', ...
                     'Z'        , 29, ...
                     'Valence'  , 11); 
metalsdb.cu.latParam = struct('a'        , 0.36146);
metalsdb.cu.SK = struct('Vsssig'   ,-0.07518, ...
                        'Vspsig'   , 0.11571, ...
                        'Vppsig'   , 0.19669, ...
                        'Vpppi'    , 0.01940, ...
                        'Vpdsig'   ,-0.03107, ...
                        'Vpdpi'    , 0.01753, ...
                        'Vsdsig'   ,-0.03107, ...
                        'Vddsig'   ,-0.02566, ...
                        'Vddpi'    , 0.01800, ...
                        'Vdddel'   ,-0.00408);
metalsdb.cu.onsite = struct('s' ,0.79466, ...
                            'p' ,1.35351, ...
                            'd1',0.37307, ...
                            'd2',0.37180);

% Zn

% 4d metals

% Y
% Zr
% Nb


metalsdb.mo = struct('name'     , 'Molybdenum', ...
                     'structure', 'BCC', ...
                     'Z'        , 42, ...
                     'Valence'  , 6); 
metalsdb.mo.latParam = struct('a'        , 0.31470);
metalsdb.mo.SK = struct('Vsssig'   ,-0.11957, ...
                        'Vspsig'   , 0.10619, ...
                        'Vppsig'   , 0.18564, ...
                        'Vpppi'    , 0.04323, ...
                        'Vpdsig'   ,-0.14707, ...
                        'Vpdpi'    , 0.02715, ...
                        'Vsdsig'   ,-0.10802, ...
                        'Vddsig'   ,-0.09948, ...
                        'Vddpi'    , 0.04647, ...
                        'Vdddel'   , 0.00093);
metalsdb.mo.onsite = struct('s' ,1.23823, ...
                            'p' ,1.67475, ...
                            'd1',0.85996, ...
                            'd2',0.77276);

% Tc


metalsdb.ru = struct('name'     , 'Ruthenium', ...
                     'structure', 'HCP', ...
                     'Z'        , 44, ...
                     'Valence'  , 8); 
metalsdb.ru.latParam = struct('a'        , 0.27058, ...
                              'c'        , 42816);
metalsdb.ru.SK = struct('Vsssig'   ,-0.07589, ...
                        'Vspsig'   , 0.09273, ...
                        'Vppsig'   , 0.07019, ...
                        'Vpppi'    ,-0.07048, ...
                        'Vpdsig'   , 0.07927, ...
                        'Vpdpi'    ,-0.03384, ...
                        'Vsdsig'   , 0.06440, ...
                        'Vddsig'   ,-0.08143, ...
                        'Vddpi'    , 0.04049, ...
                        'Vdddel'   ,-0.00497);
metalsdb.ru.onsite = struct('s' ,1.21824, ...
                            'p' ,1.34284, ...
                            'd0',0.65178, ...
                            'd1',0.64968, ...
                            'd2',0.66649);

% Rh
% Pd


metalsdb.ag = struct('name'     , 'Silver', ...
                     'structure', 'FCC', ...
                     'Z'        , 47, ...
                     'Valence'  , 11); 
metalsdb.ag.latParam = struct('a'        , 0.40857);
metalsdb.ag.SK = struct('Vsssig'   ,-0.06581, ...
                        'Vspsig'   , 0.09781, ...
                        'Vppsig'   , 0.15752, ...
                        'Vpppi'    , 0.00649, ...
                        'Vpdsig'   ,-0.03905, ...
                        'Vpdpi'    , 0.01519, ...
                        'Vsdsig'   ,-0.03110, ...
                        'Vddsig'   ,-0.03151, ...
                        'Vddpi'    , 0.01757, ...
                        'Vdddel'   ,-0.00336);
metalsdb.ag.onsite = struct('s' ,0.68297, ...
                            'p' ,1.13432, ...
                            'd1',0.12249, ...
                            'd2',0.12006);

% Cd


% 5d metals

% Lu
% Hf
% Ta


metalsdb.w  = struct('name'     , 'Tungsten', ...
                     'structure', 'BCC', ...
                     'Z'        , 74, ...
                     'Valence'  , 6); 
metalsdb.w.latParam = struct('a'        , 0.31652);
metalsdb.w.SK = struct('Vsssig'   ,-0.11258, ...
                       'Vspsig'   , 0.09945, ...
                       'Vppsig'   , 0.19331, ...
                       'Vpppi'    , 0.04787, ...
                       'Vpdsig'   ,-0.18136, ...
                       'Vpdpi'    , 0.02424, ...
                       'Vsdsig'   ,-0.11301, ...
                       'Vddsig'   ,-0.11837, ...
                       'Vddpi'    , 0.05194, ...
                       'Vdddel'   ,0.00248);
metalsdb.w.onsite = struct('s' ,0.99861, ...
                           'p' ,1.68521, ...
                           'd1',0.96813, ...
                           'd2',0.85720);

% Re


metalsdb.os = struct('name'     , 'Osmium', ...
                     'structure', 'HCP', ...
                     'Z'        , 76, ...
                     'Valence'  , 8); 
metalsdb.os.latParam = struct('a'        , 0.27341, ...
                              'c'        , 0.43918);
metalsdb.os.SK = struct('Vsssig'   ,-0.08605, ...
                        'Vspsig'   , 0.11762, ...
                        'Vppsig'   , 0.11915, ...
                        'Vpppi'    ,-0.04613, ...
                        'Vpdsig'   , 0.10441, ...
                        'Vpdpi'    ,-0.03664, ...
                        'Vsdsig'   , 0.07972, ...
                        'Vddsig'   ,-0.10118, ...
                        'Vddpi'    , 0.04527, ...
                        'Vdddel'   ,-0.00426);
metalsdb.os.onsite = struct('s' ,1.04541, ...
                            'p' ,1.51468, ...
                            'd0',0.73187, ...
                            'd1',0.72480, ...
                            'd2',0.74935);

% Ir
% Pt


metalsdb.au = struct('name'     , 'Gold', ...
                     'structure', 'FCC', ...
                     'Z'        , 79, ...
                     'Valence'  , 11); 
metalsdb.au.latParam = struct('a'        , 0.40782);
metalsdb.au.SK = struct('Vsssig'   ,-0.06680, ...
                        'Vspsig'   , 0.09721, ...
                        'Vppsig'   , 0.17866, ...
                        'Vpppi'    ,-0.01645, ...
                        'Vpdsig'   ,-0.06399, ...
                        'Vpdpi'    , 0.01896, ...
                        'Vsdsig'   ,-0.04722, ...
                        'Vddsig'   ,-0.04971, ...
                        'Vddpi'    , 0.02624, ...
                        'Vdddel'   ,-0.00457);
metalsdb.au.onsite = struct('s' ,0.56220, ...
                            'p' ,1.27897, ...
                            'd1',0.26097, ...
                            'd2',0.25309);

% Hg

end